In [44]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

In [45]:
df = pd.read_csv("C:\\Users\\Mukund\\Downloads\\Premier League 2024-25 stats.csv")
df.head()

,Player Name,Club,Nationality,Position,Appearances,Minutes,Goals,Assists,Shots,Shots On Target,...,Fouls,Yellow Cards,Red Cards,Saves,Saves %,Penalties Saved,Clearances Off Line,Punches,High Claims,Goals Prevented
0,Ben White,Arsenal,England,DEF,17,1198,0,2,9,12,...,10,2,0,0,0%,0,0,0,0,0.0
1,Bukayo Saka,Arsenal,England,MID,25,1735,6,10,67,2,...,15,3,0,0,0%,0,0,0,0,0.0
2,David Raya,Arsenal,Spain,GKP,38,3420,0,0,0,0,...,1,3,0,86,72%,0,0,8,53,2.1
3,Declan Rice,Arsenal,England,MID,35,2833,4,7,48,18,...,21,5,1,0,0%,0,0,0,0,0.0
4,Ethan Nwaneri,Arsenal,England,MID,26,889,4,0,24,0,...,9,1,0,0,0%,0,0,0,0,0.0

In [46]:
df.columns

Index(['Player Name', 'Club', 'Nationality', 'Position', 'Appearances',
       'Minutes', 'Goals', 'Assists', 'Shots', 'Shots On Target',
       'Conversion %', 'Big Chances Missed', 'Hit Woodwork', 'Offsides',
       'Touches', 'Passes', 'Successful Passes', 'Passes%', 'Crosses',
       'Successful Crosses', 'Crosses %', 'fThird Passes',
       'Successful fThird Passes', 'fThird Passes %', 'Through Balls',
       'Carries', 'Progressive Carries', 'Carries Ended with Goal',
       'Carries Ended with Assist', 'Carries Ended with Shot',
       'Carries Ended with Chance', 'Possession Won', 'Dispossessed',
       'Clean Sheets', 'Clearances', 'Interceptions', 'Blocks', 'Tackles',
       'Ground Duels', 'gDuels Won', 'gDuels %', 'Aerial Duels', 'aDuels Won',
       'aDuels %', 'Goals Conceded', 'xGoT Conceded', 'Own Goals', 'Fouls',
       'Yellow Cards', 'Red Cards', 'Saves', 'Saves %', 'Penalties Saved',
       'Clearances Off Line', 'Punches', 'High Claims', 'Goals Prevented'],
      dtype='object')

In [47]:
position_map = {
    'FW': 'Forward', 'FWD': 'Forward', 'ST': 'Forward',
    'MF': 'Midfielder', 'MID': 'Midfielder', 'CM': 'Midfielder', 'AM': 'Midfielder', 'DM': 'Midfielder',
    'DF': 'Defender', 'DEF': 'Defender', 'CB': 'Defender', 'LB': 'Defender', 'RB': 'Defender',
    'GK': 'Goalkeeper', 'Goalie': 'Goalkeeper', 'GKP' : 'Goalkeeper'
}

df['Position'] = df['Position'].replace(position_map)

In [48]:
percent_cols = ['Conversion %', 'Crosses %', 'Passes%', 'fThird Passes %', 'gDuels %', 'aDuels %', 'Saves %']

for col in percent_cols:
    df[col] = df[col].str.rstrip('%').astype(float)

df.head()

,Player Name,Club,Nationality,Position,Appearances,Minutes,Goals,Assists,Shots,Shots On Target,...,Fouls,Yellow Cards,Red Cards,Saves,Saves %,Penalties Saved,Clearances Off Line,Punches,High Claims,Goals Prevented
0,Ben White,Arsenal,England,Defender,17,1198,0,2,9,12,...,10,2,0,0,0.0,0,0,0,0,0.0
1,Bukayo Saka,Arsenal,England,Midfielder,25,1735,6,10,67,2,...,15,3,0,0,0.0,0,0,0,0,0.0
2,David Raya,Arsenal,Spain,Goalkeeper,38,3420,0,0,0,0,...,1,3,0,86,72.0,0,0,8,53,2.1
3,Declan Rice,Arsenal,England,Midfielder,35,2833,4,7,48,18,...,21,5,1,0,0.0,0,0,0,0,0.0
4,Ethan Nwaneri,Arsenal,England,Midfielder,26,889,4,0,24,0,...,9,1,0,0,0.0,0,0,0,0,0.0

In [49]:
numeric_cols = df.columns.difference(['Player Name', 'Club', 'Nationality', 'Position'])  # exclude non-numeric
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors='coerce')

In [50]:
df.head()

,Player Name,Club,Nationality,Position,Appearances,Minutes,Goals,Assists,Shots,Shots On Target,...,Fouls,Yellow Cards,Red Cards,Saves,Saves %,Penalties Saved,Clearances Off Line,Punches,High Claims,Goals Prevented
0,Ben White,Arsenal,England,Defender,17,1198,0,2,9,12,...,10,2,0,0,0.0,0,0,0,0,0.0
1,Bukayo Saka,Arsenal,England,Midfielder,25,1735,6,10,67,2,...,15,3,0,0,0.0,0,0,0,0,0.0
2,David Raya,Arsenal,Spain,Goalkeeper,38,3420,0,0,0,0,...,1,3,0,86,72.0,0,0,8,53,2.1
3,Declan Rice,Arsenal,England,Midfielder,35,2833,4,7,48,18,...,21,5,1,0,0.0,0,0,0,0,0.0
4,Ethan Nwaneri,Arsenal,England,Midfielder,26,889,4,0,24,0,...,9,1,0,0,0.0,0,0,0,0,0.0

In [51]:
df['Goal Contributions'] = df['Goals']+df['Assists']

In [52]:
df['Shot Accuracy'] = (df['Shots On Target'] / df['Shots'])
df.head()

,Player Name,Club,Nationality,Position,Appearances,Minutes,Goals,Assists,Shots,Shots On Target,...,Red Cards,Saves,Saves %,Penalties Saved,Clearances Off Line,Punches,High Claims,Goals Prevented,Goal Contributions,Shot Accuracy
0,Ben White,Arsenal,England,Defender,17,1198,0,2,9,12,...,0,0,0.0,0,0,0,0,0.0,2,1.333333
1,Bukayo Saka,Arsenal,England,Midfielder,25,1735,6,10,67,2,...,0,0,0.0,0,0,0,0,0.0,16,0.029851
2,David Raya,Arsenal,Spain,Goalkeeper,38,3420,0,0,0,0,...,0,86,72.0,0,0,8,53,2.1,0,NaN
3,Declan Rice,Arsenal,England,Midfielder,35,2833,4,7,48,18,...,1,0,0.0,0,0,0,0,0.0,11,0.375000
4,Ethan Nwaneri,Arsenal,England,Midfielder,26,889,4,0,24,0,...,0,0,0.0,0,0,0,0,0.0,4,0.000000

In [53]:
df.columns

Index(['Player Name', 'Club', 'Nationality', 'Position', 'Appearances',
       'Minutes', 'Goals', 'Assists', 'Shots', 'Shots On Target',
       'Conversion %', 'Big Chances Missed', 'Hit Woodwork', 'Offsides',
       'Touches', 'Passes', 'Successful Passes', 'Passes%', 'Crosses',
       'Successful Crosses', 'Crosses %', 'fThird Passes',
       'Successful fThird Passes', 'fThird Passes %', 'Through Balls',
       'Carries', 'Progressive Carries', 'Carries Ended with Goal',
       'Carries Ended with Assist', 'Carries Ended with Shot',
       'Carries Ended with Chance', 'Possession Won', 'Dispossessed',
       'Clean Sheets', 'Clearances', 'Interceptions', 'Blocks', 'Tackles',
       'Ground Duels', 'gDuels Won', 'gDuels %', 'Aerial Duels', 'aDuels Won',
       'aDuels %', 'Goals Conceded', 'xGoT Conceded', 'Own Goals', 'Fouls',
       'Yellow Cards', 'Red Cards', 'Saves', 'Saves %', 'Penalties Saved',
       'Clearances Off Line', 'Punches', 'High Claims', 'Goals Prevented',
       'Goal Contributions', 'Shot Accuracy'],
      dtype='object')

In [54]:
df['Fair Play'] = (df['Yellow Cards'] + df['Red Cards'])/df['Appearances']

In [55]:
df['Defensiveness'] = (df['Possession Won'] + df['Clearances'] + df['Interceptions'] + df['Tackles'] + df['gDuels Won'] + df['aDuels Won']+df['Blocks'])

In [56]:
df['Ariel Threat'] = (df['aDuels Won']/df['Aerial Duels'])

In [57]:
df.drop('aDuels %',axis=1)

,Player Name,Club,Nationality,Position,Appearances,Minutes,Goals,Assists,Shots,Shots On Target,...,Penalties Saved,Clearances Off Line,Punches,High Claims,Goals Prevented,Goal Contributions,Shot Accuracy,Fair Play,Defensiveness,Ariel Threat
0,Ben White,Arsenal,England,Defender,17,1198,0,2,9,12,...,0,0,0,0,0.0,2,1.333333,0.117647,315,0.312500
1,Bukayo Saka,Arsenal,England,Midfielder,25,1735,6,10,67,2,...,0,0,0,0,0.0,16,0.029851,0.120000,165,0.511111
2,David Raya,Arsenal,Spain,Goalkeeper,38,3420,0,0,0,0,...,0,0,8,53,2.1,0,NaN,0.078947,29,NaN
3,Declan Rice,Arsenal,England,Midfielder,35,2833,4,7,48,18,...,0,0,0,0,0.0,11,0.375000,0.171429,373,0.384615
4,Ethan Nwaneri,Arsenal,England,Midfielder,26,889,4,0,24,0,...,0,0,0,0,0.0,4,0.000000,0.038462,15,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557,Santiago Bueno,Wolverhampton Wanderers,Uruguay,Defender,29,1682,0,0,6,3,...,0,0,0,0,0.0,0,0.500000,0.068966,376,0.431818
558,Tom King,Wolverhampton Wanderers,Wales,Goalkeeper,1,1,0,0,0,0,...,0,0,0,0,0.0,0,NaN,0.000000,0,NaN
559,Tommy Doyle,Wolverhampton Wanderers,England,Midfielder,24,475,0,1,9,0,...,0,0,0,0,0.0,1,0.000000,0.041667,22,NaN
560,Toti Gomes,Wolverhampton Wanderers,Portugal,Defender,31,2615,0,0,7,8,...,0,2,0,0,0.0,0,1.142857,0.225806,481,0.187500
561,Yerson Mosquera,Wolverhampton Wanderers,Colombia,Defender,5,442,0,0,2,0,...,0,1,0,0,0.0,0,0.000000,0.400000,25,NaN

In [58]:
df.drop('Saves %',axis=1)

,Player Name,Club,Nationality,Position,Appearances,Minutes,Goals,Assists,Shots,Shots On Target,...,Penalties Saved,Clearances Off Line,Punches,High Claims,Goals Prevented,Goal Contributions,Shot Accuracy,Fair Play,Defensiveness,Ariel Threat
0,Ben White,Arsenal,England,Defender,17,1198,0,2,9,12,...,0,0,0,0,0.0,2,1.333333,0.117647,315,0.312500
1,Bukayo Saka,Arsenal,England,Midfielder,25,1735,6,10,67,2,...,0,0,0,0,0.0,16,0.029851,0.120000,165,0.511111
2,David Raya,Arsenal,Spain,Goalkeeper,38,3420,0,0,0,0,...,0,0,8,53,2.1,0,NaN,0.078947,29,NaN
3,Declan Rice,Arsenal,England,Midfielder,35,2833,4,7,48,18,...,0,0,0,0,0.0,11,0.375000,0.171429,373,0.384615
4,Ethan Nwaneri,Arsenal,England,Midfielder,26,889,4,0,24,0,...,0,0,0,0,0.0,4,0.000000,0.038462,15,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557,Santiago Bueno,Wolverhampton Wanderers,Uruguay,Defender,29,1682,0,0,6,3,...,0,0,0,0,0.0,0,0.500000,0.068966,376,0.431818
558,Tom King,Wolverhampton Wanderers,Wales,Goalkeeper,1,1,0,0,0,0,...,0,0,0,0,0.0,0,NaN,0.000000,0,NaN
559,Tommy Doyle,Wolverhampton Wanderers,England,Midfielder,24,475,0,1,9,0,...,0,0,0,0,0.0,1,0.000000,0.041667,22,NaN
560,Toti Gomes,Wolverhampton Wanderers,Portugal,Defender,31,2615,0,0,7,8,...,0,2,0,0,0.0,0,1.142857,0.225806,481,0.187500
561,Yerson Mosquera,Wolverhampton Wanderers,Colombia,Defender,5,442,0,0,2,0,...,0,1,0,0,0.0,0,0.000000,0.400000,25,NaN

In [59]:
df['Saves per conceded'] = df['Saves']/df['Goals Conceded']
df.head()

,Player Name,Club,Nationality,Position,Appearances,Minutes,Goals,Assists,Shots,Shots On Target,...,Clearances Off Line,Punches,High Claims,Goals Prevented,Goal Contributions,Shot Accuracy,Fair Play,Defensiveness,Ariel Threat,Saves per conceded
0,Ben White,Arsenal,England,Defender,17,1198,0,2,9,12,...,0,0,0,0.0,2,1.333333,0.117647,315,0.312500,NaN
1,Bukayo Saka,Arsenal,England,Midfielder,25,1735,6,10,67,2,...,0,0,0,0.0,16,0.029851,0.120000,165,0.511111,NaN
2,David Raya,Arsenal,Spain,Goalkeeper,38,3420,0,0,0,0,...,0,8,53,2.1,0,NaN,0.078947,29,NaN,2.529412
3,Declan Rice,Arsenal,England,Midfielder,35,2833,4,7,48,18,...,0,0,0,0.0,11,0.375000,0.171429,373,0.384615,NaN
4,Ethan Nwaneri,Arsenal,England,Midfielder,26,889,4,0,24,0,...,0,0,0,0.0,4,0.000000,0.038462,15,NaN,NaN

In [60]:
df.isnull().sum()

Player Name             0
Club                    0
Nationality             0
Position                0
Appearances             0
                     ...
Shot Accuracy         105
Fair Play               0
Defensiveness           0
Ariel Threat          267
Saves per conceded    519
Length: 63, dtype: int64

In [61]:
df['Saves per conceded'] = df['Saves per conceded'].fillna(0)

In [62]:
df['Shot Accuracy'] = df['Shot Accuracy'].fillna(0)

In [63]:
df['Ariel Threat'] = df['Ariel Threat'].fillna(0)

In [64]:
df.head()

,Player Name,Club,Nationality,Position,Appearances,Minutes,Goals,Assists,Shots,Shots On Target,...,Clearances Off Line,Punches,High Claims,Goals Prevented,Goal Contributions,Shot Accuracy,Fair Play,Defensiveness,Ariel Threat,Saves per conceded
0,Ben White,Arsenal,England,Defender,17,1198,0,2,9,12,...,0,0,0,0.0,2,1.333333,0.117647,315,0.312500,0.000000
1,Bukayo Saka,Arsenal,England,Midfielder,25,1735,6,10,67,2,...,0,0,0,0.0,16,0.029851,0.120000,165,0.511111,0.000000
2,David Raya,Arsenal,Spain,Goalkeeper,38,3420,0,0,0,0,...,0,8,53,2.1,0,0.000000,0.078947,29,0.000000,2.529412
3,Declan Rice,Arsenal,England,Midfielder,35,2833,4,7,48,18,...,0,0,0,0.0,11,0.375000,0.171429,373,0.384615,0.000000
4,Ethan Nwaneri,Arsenal,England,Midfielder,26,889,4,0,24,0,...,0,0,0,0.0,4,0.000000,0.038462,15,0.000000,0.000000

In [65]:
df['player_id'] = df.reset_index().index + 1

In [66]:
cols = ['player_id'] + [col for col in df.columns if col != 'player_id']
df = df[cols]
df.columns

Index(['player_id', 'Player Name', 'Club', 'Nationality', 'Position',
       'Appearances', 'Minutes', 'Goals', 'Assists', 'Shots',
       'Shots On Target', 'Conversion %', 'Big Chances Missed', 'Hit Woodwork',
       'Offsides', 'Touches', 'Passes', 'Successful Passes', 'Passes%',
       'Crosses', 'Successful Crosses', 'Crosses %', 'fThird Passes',
       'Successful fThird Passes', 'fThird Passes %', 'Through Balls',
       'Carries', 'Progressive Carries', 'Carries Ended with Goal',
       'Carries Ended with Assist', 'Carries Ended with Shot',
       'Carries Ended with Chance', 'Possession Won', 'Dispossessed',
       'Clean Sheets', 'Clearances', 'Interceptions', 'Blocks', 'Tackles',
       'Ground Duels', 'gDuels Won', 'gDuels %', 'Aerial Duels', 'aDuels Won',
       'aDuels %', 'Goals Conceded', 'xGoT Conceded', 'Own Goals', 'Fouls',
       'Yellow Cards', 'Red Cards', 'Saves', 'Saves %', 'Penalties Saved',
       'Clearances Off Line', 'Punches', 'High Claims', 'Goals Prevented',
       'Goal Contributions', 'Shot Accuracy', 'Fair Play', 'Defensiveness',
       'Ariel Threat', 'Saves per conceded'],
      dtype='object')

In [67]:
player_features = ['Goals' , 'Assists', 'Shots', 'Shot Accuracy', 'Goal Contributions', 'Defensiveness', 'Saves per conceded', 'Ariel Threat', 'Passes%']

In [68]:
X = df[player_features].fillna(0)
X.head()

,Goals,Assists,Shots,Shot Accuracy,Goal Contributions,Defensiveness,Saves per conceded,Ariel Threat,Passes%
0,0,2,9,1.333333,2,315,0.000000,0.312500,89.0
1,6,10,67,0.029851,16,165,0.000000,0.511111,87.0
2,0,0,0,0.000000,0,29,2.529412,0.000000,0.0
3,4,7,48,0.375000,11,373,0.000000,0.384615,81.0
4,4,0,24,0.000000,4,15,0.000000,0.000000,0.0

In [70]:
X.replace([np.inf, -np.inf], np.nan, inplace=True)

In [71]:
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity
X_scaled = StandardScaler().fit_transform(X)

In [72]:
X_filled = X.fillna(0)  # or use mean()
X_scaled = StandardScaler().fit_transform(X_filled)
similarity_matrix = cosine_similarity(X_scaled)

In [73]:
similar_names = []
similar_scores = []

for i, row in enumerate(similarity_matrix):
    row[i] = -1  # exclude self
    top_idx = np.argmax(row)
    similar_names.append(df.iloc[top_idx]['Player Name'])
    similar_scores.append(row[top_idx])
    
df['Most Similar Player'] = similar_names
df['Similarity Score'] = similar_scores

In [40]:
top_n = 3

similar_df = pd.DataFrame({
    'player_id': df['player_id'],
    'Player Name': df['Player Name']
})

for n in range(1, top_n + 1):
    names = []
    scores = []
    for i, row in enumerate(similarity_matrix):
        row[i] = -1  # exclude self
        top_idxs = np.argsort(row)[-top_n:][::-1]  # top N indices in descending order
        names.append(df.iloc[top_idxs[n - 1]]['Player Name'])
        scores.append(row[top_idxs[n - 1]])
    similar_df[f'Similar Player {n}'] = names
    similar_df[f'Similarity Score {n}'] = scores

In [43]:
similar_df.to_sql('player_similarity', con=engine, index=False, if_exists='replace')

562

In [39]:
df.columns

Index(['player_id', 'Player Name', 'Club', 'Nationality', 'Position',
       'Appearances', 'Minutes', 'Goals', 'Assists', 'Shots',
       'Shots On Target', 'Conversion %', 'Big Chances Missed', 'Hit Woodwork',
       'Offsides', 'Touches', 'Passes', 'Successful Passes', 'Passes%',
       'Crosses', 'Successful Crosses', 'Crosses %', 'fThird Passes',
       'Successful fThird Passes', 'fThird Passes %', 'Through Balls',
       'Carries', 'Progressive Carries', 'Carries Ended with Goal',
       'Carries Ended with Assist', 'Carries Ended with Shot',
       'Carries Ended with Chance', 'Possession Won', 'Dispossessed',
       'Clean Sheets', 'Clearances', 'Interceptions', 'Blocks', 'Tackles',
       'Ground Duels', 'gDuels Won', 'gDuels %', 'Aerial Duels', 'aDuels Won',
       'aDuels %', 'Goals Conceded', 'xGoT Conceded', 'Own Goals', 'Fouls',
       'Yellow Cards', 'Red Cards', 'Saves', 'Saves %', 'Penalties Saved',
       'Clearances Off Line', 'Punches', 'High Claims', 'Goals Prevented',
       'Goal Contributions', 'Shot Accuracy', 'Fair Play', 'Defensiveness',
       'Ariel Threat', 'Saves per conceded', 'Most Similar Player',
       'Similarity Score'],
      dtype='object')

In [ ]:
top_n = 3

similar_df = pd.DataFrame({
    'player_id': df['player_id'],
    'Player Name': df['Player Name']
})

for n in range(1, top_n + 1):
    names = []
    scores = []
    for i, row in enumerate(similarity_matrix):
        row[i] = -1  # exclude self
        top_idxs = np.argsort(row)[-top_n:][::-1]  # top N indices in descending order
        names.append(df.iloc[top_idxs[n - 1]]['Player Name'])
        scores.append(row[top_idxs[n - 1]])
    similar_df[f'Similar Player {n}'] = names
    similar_df[f'Similarity Score {n}'] = scores

In [42]:
from sqlalchemy import create_engine

db_name = "EPL"
username = "postgres"
password = "200197"
host = "localhost"
port = "5432"  # default

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{db_name}")

In [49]:
df.to_sql("PL", engine, if_exists="replace", index=False)

67